language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: true
deploy:
  provider: pypi
  user: cchen
  password:
    secure: axvhev39fJOk3XrOdAyaFvIdo3xVI0ZQYIjIlQE2ayMYeIZ/Dqeget/FCBv7VmgzbBDl8GGpK+PNtRjbKHUsptimB9csM9sXgv2o/WXlwEZaqj6dmnD4wPGxJJKfY1chXblFLFE12CEwE6nQx9CAnHM9O4Eiiopd1wSNZKuOTFC/QTp6DMgP4BdnSxwXGVWNtC50spUEHJ5M4mPfdzD8xksGYVUFSp8RU0aa/H6w6E/OlRbzqLU4rn60NetChCJ3A8MAcV+FY9Qo3bT8VnRZ7s1zJEWO9QRVWodykfgFaQ99AbR7s/p478czk82DOS5LDX4ebKtDHkv/jHzdAA4ggx6UcsnhDpv9/OfTK5GRPYxZim90/mwPJh7DH6RaheP2PPDVaQF76cMZk7111BYrQyoDEqLAy1QJIYZJ2G4AlVE6JRjBkKUFKcotSGsmDGa6seb60+LFpSV7kADZEfow7sSF4aKpDqZGIFWz+QnFHAFHBI6qP6bD/ZNthdawf37DDNlkg8wq1mdBkGBjjEohgww8IJhA7TJx09dQGfUlb1yZjFgpIvSAGSSHs3yz1yLgk9DysQ4NQESwg05mnadOwO7fv1MdqbslCxUt/LZ+ksB3+r6BTQVzrA0S/a4MSIBGJ0sqIOj/yg1/+KhQij/Jf9gaT38jZTzGuKB1JyW0dbY=
true:
  python: 2.7
  branch: master
