language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: true
deploy:
  provider: pypi
  user: cchen
  password:
    secure: MjCCd91pAeolCGrc2LVq3vVLtnadOfD6Lhtg1A5qNTs6JLc9zopjrV9e299/DZz6lpJZDjEmV1Ap4PdoF+OEb/SkaabhK94dwe1S9L9imOfhUAT7ZKgevQFykuiaIVExluFzndx8/eJ6xFNPg7FevMwyWgiuK8Fzeh1nAiger3P9WLMXRvJO2Ez30ODrEGg3pR+KhXYWFtqIrmaR7pm22AP5z0XdlBYdDko08DRpMuLZ+JEb8tkSi1m8BugLdVxaW8oniymwicr2TPL6Hm+Cc4Pj0neLmf7j8vSvdlgAiGxApaM8j/rq1Qh3ZCKUrPPrWnUQ84wHUS48CxEgON17aJJRI3OSj8zdADlLDweDajxL90yUL+IGVuFDjX3aQXSRJdjuT9rqH1cWyHlJW1LKfxNftrogDJNKt0Cje5yxY1eyVjzuKLX3fZABjUtkQBB2cobWEjcS7q3U+43c7FWVuRcek9oqd4VMo6wx4atcvdgqzLtzf90C46hMe2UlS1Wcz5SF5egRKWJSEOTPf2Md9UsSNXo5YniPxKsE778KzsCDQPMkMZWaSyfTlREJNdJcZvw8WOw3HvkMd401TJIoJb+75K2D7FQ9547r3XVJGATJLCia+HR5gydaSv16IKqqmQqlLRkrpi35E6eHg2UWuM2RQAhMzD9n7/sLhppHFLk=
true:
  python: 2.7
  branch: master
